apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.productpage.service.type }}
  ports:
    - port: {{ .Values.productpage.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: productpage
    release: {{ .Release.Name }}
