apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  metadata:
  name: {{ template "bookinfo.fullname" . }}
  labels:
    app: {{ template "bookinfo.name" . }}
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bookinfo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bookinfo.name" . }}
        release: {{ .Release.Name }}
        version: v1
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: {{ .Values.productpage.service.port }}