apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  metadata:
  name: reviews-v3
  labels:
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.reviews.replicas }}
  selector:
    matchLabels:
      app: reviews
      release: {{ .Release.Name }}
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        release: {{ .Release.Name }}
        version: v3
    spec:
      containers:
      - name: ratings
        image: quay.io/jackzzj/examples-bookinfo-reviews-v3:1.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        livenessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
